server {
    listen 80;
    server_name kiwihub.com www.kiwihub.com 47.109.26.32 localhost;

    # =========================================================
    # 1. 前端首页
    # =========================================================
    location / {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    # =========================================================
    # 2. 全局 Swagger 静态资源
    # =========================================================
    location ~ ^/(webjars|v3|swagger-resources) {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        if ($http_referer ~* "/users/") {
            proxy_pass http://kiwi-user:8070;
        }
        if ($http_referer ~* "/links/") {
            proxy_pass http://kiwi-link:8030;
        }
        proxy_pass http://kiwi-content:8010;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    # =========================================================
    # 3. Kiwi-User (用户服务)
    # =========================================================
    location /api/users/ {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://kiwi-user:8070;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Prefix /api;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    location /users/ {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        rewrite ^/users/(.*)$ /$1 break;
        proxy_pass http://kiwi-user:8070;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Prefix /api;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    # =========================================================
    # 4. Kiwi-Link (短链服务)
    # =========================================================
    location /api/links/ {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://kiwi-link:8030;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Prefix /api;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    location /links/ {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        rewrite ^/links/(.*)$ /$1 break;
        proxy_pass http://kiwi-link:8030;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Prefix /api;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    # =========================================================
    # 5. Kiwi-Content (内容服务)
    # =========================================================
    location /api/ {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://kiwi-content:8010;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Prefix /api;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }

    location /content/ {
        include /opt/kiwihub/nginx/config/cors_options.conf;
        rewrite ^/content/(.*)$ /$1 break;
        proxy_pass http://kiwi-content:8010;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Prefix /api;
        include /opt/kiwihub/nginx/config/cors_headers.conf;
    }
}
