spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      password: ${NACOS_USERNAME:nacos}
      username: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:dev}
        group: kiwi-hub
      config:
        import-check:
          enabled: false
        namespace: ${NACOS_NAMESPACE:dev}
        group: kiwi-hub
  config:
    import:
      - nacos:kiwi-content-mongodb.yml
      - nacos:kiwi-content-rabbitmq.yml
      - nacos:kiwi-content-redis.yml