spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
      discovery:
        namespace: dev
        group: kiwi-hub
      config:
        import-check:
          enabled: false
        namespace: dev
        group: kiwi-hub
  config:
    import:
      - nacos:kiwi-content-mongodb.yml
      - nacos:kiwi-content-mysql.yml
      - nacos:kiwi-content-redis.yml
      - nacos:kiwi-redis-session.yml
      - nacos:kiwi-knife4j-content.yml